/*
 **************************************************************
 * AM2320_temperature_humidity.c
 * Author: Tom
 * Date: 18/01/2023
 * AVR Library for the AM2320 temperature and humidity
 * sensor. This lib requires the Peter Fleury i2cmaster 
 * interface.
 **************************************************************
 * EXTERNAL FUNCTIONS
 **************************************************************
 * AM2320_wake_up() - Wake the AM2320.
 * AM2320_update_temperature_humidity() - Update the current
 * readings for temperature and humidity.
 * AM2320_get_temperature_float_celsius() - Get the current
 * reading for temp as a float in degrees Celsius.
 * AM2320_get_temperature_string_celsius() - Get current reading
 * for temperature as a string in degrees Celsius.
 * AM2320_get_humidity_float() - Get current reading for
 * humidity as a float.
 * AM2320_get_humidity_string() - Get current reading for
 * humidity as a string.
 **************************************************************
*/

#include <avr/io.h>
#include <stdio.h>
#include <stdlib.h>

#define F_CPU 16000000L	/* Clock frequency of CPU */
#include <util/delay.h>

#include "AM2320_temperature_humidity.h"
#include "../pFleury_i2c_stuff/i2cmaster.h"

/* 
Temperature and humidity readings stored here. 
Index:
  0 = temperature.
  1 = humidity .
*/
static float _temperatureHumidity[2];

/* 
Raw data from reading temp and humidity.
Index:
  0 = Function Code.
  1 = Number of Bytes read from registers.
  2 = High byte of Humidity reading. 
  3 = Low byte of Humidity reading.
  4 = High byte of Temperature reading.
  5 = Low byte of Temperature reading.
  6 = Low byte of CRC code.
  7 = High byte of CRC code. 
*/
static uint8_t _rawData[8];

/*
* AM2320_wake_up()
* -------------
* External function to wake the AM2320 Temperature and 
* Humidity sensor.
* Need to wake up the device before attempting to 
* communicate.
* The sensor sleeps after the temp and humidity registers
* have been read.
*/
void AM2320_wake_up() {
	i2c_set_bitrate(AM2320_I2C_BITRATE);
	i2c_start(AM2320_ADDR | AM2320_I2C_WRITE);
	i2c_write(AM2320_WAKE_UP_COMMAND);
	i2c_stop();
	
	/* Minimum 800us delay required after 
	wakeup sequence according to datasheet */
	_delay_us(800); 
}

/*
* AM2320_update_temperature_humidity()
* -----------------------------------
* External function to read the current temperature and 
* humidity from the AM2320 sensor. The values are stored 
* in the _temperature_humidity array found at the top of 
* this file.
* Temperature is in degrees Celsius and humidity
* from 0-99.9 %
*
* NOTE: Call this function at most ONCE every 2 seconds.
* The data sheet states this reduces the amount of heat
* generated by the component and gives more accurate 
* readings.
*/
void AM2320_update_temperature_humidity() {
	int16_t temperature;
	uint16_t humidity;
	
	AM2320_wake_up();
	i2c_start(AM2320_ADDR | AM2320_I2C_WRITE);
	i2c_write(AM2320_COMMAND_READ_REG_DATA);
	i2c_write(AM2320_HUMIDITY_REG_HIGH);
	i2c_write(0x04); /* Read 4 registers */
	i2c_stop();
	
	/* Wait at least 1.5ms for sensor */
	_delay_ms(2); 
	
	/* Receive data from sensor */
	i2c_start(AM2320_ADDR | AM2320_I2C_READ);
	for(uint8_t i = 0; i < 8; i++) {
		_rawData[i] = i2c_readAck();
	}
	_rawData[8] = i2c_readNak(); /* Last read must be a NAK */
	i2c_stop();
	
	/* Construct temporary calculations for temp and humidity
	from the received data */
	humidity = ((uint16_t)_rawData[2] << 8) | _rawData[3];
	temperature = ((int16_t)_rawData[4] << 8) | _rawData[5];
	
	/* Check if humidity is in appropriate range */
	if ((humidity > 999) || (humidity <= 0)) {
		/* -111 signals an error */
		 _temperatureHumidity[1] = -111; 
	} else {
		/* Actual calculation for humidity as a float */
		_temperatureHumidity[1] = humidity / 10.0; 
	}
	
	/* Check if temperature is in appropriate range */
	if ((temperature > 800) || (temperature < -400)) {
		/* -111 signals an error */
		_temperatureHumidity[0] = -111;
	} else {
		/* Actual calculation for temperature as a float */
		_temperatureHumidity[0] = temperature / 10.0;
	}
}

/*
* AM2320_get_temperature_float_celsius()
* --------------------------------------
* External function that returns the last recorded 
* temperature from the sensor as a float in degrees Celsius.
*/
float AM2320_get_temperature_float_celsius() {
	return _temperatureHumidity[0];
}

/*
* AM2320_get_temperature_string_celsius()
* ---------------------------------------
* External function that returns the last recorded temperature 
* from the sensor as a string in degrees Celsius.
*/
void AM2320_get_temperature_string_celsius(char string[7]) {
	if (_temperatureHumidity[0] == -111) {
		string[0] = 'e';
		string[1] = 'r';
		string[2] = 'r';
		string[3] = '\0';
		return;
	}
	dtostrf(_temperatureHumidity[0], 2, 1, string);
}

/*
* AM2320_get_humidity_float()
* ---------------------------
* External function that returns the last recorded humidity 
* from the sensor as a float.
*/
float AM2320_get_humidity_float() {
	return _temperatureHumidity[1];
}

/*
* AM2320_get_humidity_string()
* -------------------------------
* External function that returns the last recorded humidity 
* from the sensor as a string.
*/
void AM2320_get_humidity_string(char string[5]) {
	if (_temperatureHumidity[1] == -111) {
		string[0] = 'e';
		string[1] = 'r';
		string[2] = 'r';
		string[3] = '\0';
		return;
	}
	dtostrf(_temperatureHumidity[1], 2, 1, string);
}
